services:
  convert:
    build:
      context: .
      dockerfile: .docker/Convert.dockerfile
    volumes:
      - ./converter:/src
      - ./tiffs:/data/tiffs
      - ./terrarium:/data/terrarium
    command: python convert.py