services:
  convert:
    build:
      context: .
      dockerfile: .docker/Convert.dockerfile
    volumes:
      - ./converter:/converter
      - ./tiffs:/converter/tiffs
      - ./terrarium:/converter/terrarium
    command: python convert.py