services:
  convert:
    build:
      context: .
      dockerfile: .docker/Transform.dockerfile
    volumes:
      - ./transform:/src
      - ./tiff:/data/tiff
      - ./terrarium:/data/terrarium
    command: python convert.py

  cut:
    build:
      context: .
      dockerfile: .docker/Transform.dockerfile
    volumes:
      - ./transform:/src
      - ./tiff:/data/tiff
    entrypoint: python cut.py