services:
  convert:
    build:
      context: .
      dockerfile: .docker/Convert.dockerfile
    volumes:
      - ./converter:/src
      - ./tiffs:/data
      - ./terrarium:/data
    command: python convert.py