name: build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  hillshader:
    runs-on: ${{ matrix.host.image }}

    strategy:
      # Cancel all in-progress and queued jobs in the matrix if any job in the matrix fails
      fail-fast: true

      # Set up a matrix to run the different configurations:
      matrix:
        build_type: [Debug, RelWithDebInfo, Release, MinSizeRel]
        # image states
        # windows-2022: https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md
        host:
          - { image: windows-2022, preset_prefix: dest-win-gha }

    env:
      VCPKG_BINARY_CACHE: ${{ github.workspace }}/.vcpkg_binary_cache
      VCPKG_BINARY_SOURCES: clear;files,${{ github.workspace }}/.vcpkg_binary_cache,readwrite
      VCPKG_FEATURE_FLAGS: manifests,binarycaching

    steps:
      - name: checkout
        uses: actions/checkout@v3

      # Use this to set up an open ssh debugging session with CI
      # - name: Setup ssh session
      #   uses: lhotari/action-upterm@v1

      - name: Set reusable strings
        # Turn repeated input strings (such as the presets) into step outputs. These step outputs can be used throughout the workflow file.
        id: strings
        shell: bash
        run: |
          echo "configure-preset=${{ matrix.host.preset_prefix }}-${{ matrix.build_type }}" >> "$GITHUB_OUTPUT"
          echo "build-preset=${{ matrix.host.preset_prefix }}-${{ matrix.build_type }}" >> "$GITHUB_OUTPUT"

      - name: Cache vcpkg downloads
        uses: actions/cache@v4
        with:
          path: ${{ env.VCPKG_ROOT }}/downloads
          key: vcpkgdl-${{ matrix.host.image }}-manifest:${{ hashFiles('vcpkg.json', 'vcpkg-configuration.json') }}
          restore-keys: |
            vcpkgdl-${{ matrix.host.image }}

      - name: Cache vcpkg binaries
        uses: actions/cache@v4
        with:
          path: ${{ env.VCPKG_BINARY_CACHE }}
          key: >
            vcpkgbin-${{ matrix.host.image }}-${{ matrix.build_type }}-${{ matrix.host.preset_prefix }}
            -manifest:${{ hashFiles('vcpkg.json', 'vcpkg-configuration.json') }}

      - name: sccache
        uses: hendrikmuhs/ccache-action@v1.2
        if: runner.os == 'Windows'
        with:
          variant: sccache
          key: ccache-${{ matrix.host.image }}-${{ matrix.build_type }}-${{ matrix.host.preset_prefix }}
          max-size: 500M

      - name: Setup MSVC dev environment
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure CMake
        run: >
          cmake --preset ${{ steps.strings.outputs.configure-preset }}
          -DCMAKE_C_COMPILER_LAUNCHER=sccache
          -DCMAKE_CXX_COMPILER_LAUNCHER=sccache

      - name: Build
        run: cmake --build --preset ${{ steps.strings.outputs.build-preset }}

  transform:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      # Use this to set up an open ssh debugging session with CI
      # - name: Setup ssh session
      #   uses: lhotari/action-upterm@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build services
        run: docker compose build

      - name: Run cut service
        run: docker compose run --rm cut --image_bounds 0.25 0.25 0.75 0.75 tiff/example.tif tiff/cut.tif

      - name: Run convert service
        run: docker compose run --rm convert